language: node_js
node_js:
- '9'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --prod --base-href https://watermelonfarmers.github.io/watermelon-ui/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist/watermelon-ui
  on:
    branch: master
notifications:
  slack:
    secure: G9NZL7voReW6HxskHzNt4uOt3ZnfDSIOr3WPCUryfR0luU/xvxpTg+SHqnwIR06kLjlvdTRdN4Tax6SJoLZ2m5Dl+iRIAsLU4jSgA/a/37AKdmvGwaDh4jDKDhw/aMDvxTh8TiHXIve6LnRA4M3AW0O5QN7AY7EnHjK0YQ9cItWhJS1J3aFyUXK+dj1NXIZFafbjbMORCHN/fxREIR1gmMWpIhnaKRQ8k4BWALhi0LNU+nnWNpA0DWYxiN7HXqIBrMBsXxxgifbexo0gnNBhDCWGkP8G0M41stXoy6HdFApp48Bo5/EacYxeOFUxxulirCLF06cjk6+d5ZKiH2ZDjvi4aRtDT7vXYuCZ3qRx1cJ+OSjlXZzd3r9RYNJRtKTA83rHwHtUv8Ugo7zA6WThW9eqq/CG0IeIPcGdeqENq0bxbLJpMWIfCWkUhJGYufGs/rq6Iw15Sve6LspwDoEq/coAIGvNuqYGwZ9mfhJYC/I3dzJfOiBjXOkPBFCEnZfUBrAQOmd+TQq7a1IB/IRYDZYHY9u9PEtNmaBGMMedz03pgJQ//Vj2cuKIdHvHzM8yQs5BRgX2GyUhrZKzD6XKEUU/7u6PzZXRATA+U9VRaWQ2ketHxZTolaf9CVSpScUe19P51htNTVlFPoc9GyPjJtiesE823s4K9LCGvRWYUSY=
