language: node_js
node_js:
- '9'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --prod --base-href="/watermelon-ui/"
- cp dist/watermelon-ui/index.html dist/watermelon-ui/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist/watermelon-ui
  on:
    branch: master
notifications:
  slack: watermelonfarmers:0RTnAqIkXdYu4OXVWKNxXldF